// Generated by CoffeeScript 1.10.0
(function() {
  var arr, err, error, fun1, i, item, key, len, nullString, obj, obj2, str, value;

  obj = {
    a: 32,
    b: 'asdf',
    fun: function() {
      return this.a + this.b;
    }
  };

  console.log(obj.fun());

  arr = [1, 3, 5, 7, 9];

  for (i = 0, len = arr.length; i < len; i++) {
    item = arr[i];
    console.log(item);
  }

  while (arr.length > 0) {
    console.log(arr.pop());
  }

  obj2 = {
    key: 'mykey',
    value: 'myvalue',
    "class": 'my class'
  };

  for (key in obj2) {
    value = obj2[key];
    console.log(key + ":" + value);
  }

  (function() {
    return console.log('xiaoming');
  })();

  nullString = null;

  if (nullString != null) {
    console.log(nullString);
  }

  str = null;

  if (str == null) {
    str = "asdf";
  }

  console.log(str);

  fun1 = function () {
    console.log('fun1')
};

  fun1();

  try {
    a = adasdf;
  } catch (error) {
    err = error;
    console.log(err);
  } finally {
    console.log('finally');
  }

}).call(this);

//# sourceMappingURL=test.js.map
