// Generated by CoffeeScript 1.10.0
(function() {
  var db, express, router;

  express = require('express');

  router = express.Router();

  db = require('./../libs/db');

  router.get('/faq', function(req, res, next) {
    return db.users.insert({
      test: '1'
    }, function(err, doc) {
      if (err) {
        return next(err);
      }
      return res.json(doc);
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=api.js.map
