// Generated by CoffeeScript 1.10.0
(function() {
  var commonBiz, express, router, shopBiz;

  express = require('express');

  router = express.Router();

  shopBiz = require('./../bizs/shopBiz');

  commonBiz = require('../bizs/commonBiz');

  router.post('/', commonBiz.authAndSetUserInfo, shopBiz.addShop);

  router.get('/all/type/:type', shopBiz.getSomeShop);

  router.get('/all/floor/:floorId');

  router.get('/all', shopBiz.getAllShop);

  router.get('/:shopId', shopBiz.getShop);

  router.post('/shop');

  router["delete"]('/shop/:id');

  router.get('/shop/:shopId/');

  module.exports = router;

}).call(this);

//# sourceMappingURL=shop.js.map
