// Generated by CoffeeScript 1.10.0
(function() {
  var commonBiz, db, express, router, uploadBiz;

  express = require('express');

  router = express.Router();

  db = require('./../libs/db');

  commonBiz = require('../bizs/commonBiz');

  uploadBiz = require('../bizs/uploadBiz');

  router.post('/avatar', commonBiz.authAndSetUserInfo, uploadBiz.uploadAvatar);

  module.exports = router;

}).call(this);

//# sourceMappingURL=upload.js.map
