// Generated by CoffeeScript 1.10.0
(function() {
  var commonBiz, express, router, windowBiz;

  express = require('express');

  router = express.Router();

  windowBiz = require('./../bizs/windowBiz');

  commonBiz = require('../bizs/commonBiz');

  router.post('/', commonBiz.authAndSetUserInfo, windowBiz.addWindow);

  router.get('/:id', commonBiz.authAndSetUserInfo, windowBiz.getWindow);

  router.put('/:id', commonBiz.authAndSetUserInfo, windowBiz.updateWindow);

  router["delete"]('/:id', commonBiz.authAndSetUserInfo, windowBiz.removeWindow);

  router.get('/', commonBiz.authAndSetUserInfo, windowBiz.getAllWindows);

  module.exports = router;

}).call(this);

//# sourceMappingURL=window.js.map
