// Generated by CoffeeScript 1.10.0
(function() {
  var path;

  path = require('path');

  module.exports = {
    port: 7410,
    dbFilePath: path.join(__dirname, './../database/'),
    dbPath: 'mongodb://localhost/myapi',
    secret: 'token secret',
    tokenExpiredTime: 1000 * 60 * 60 * 24
  };

}).call(this);

//# sourceMappingURL=config.js.map
