// Generated by CoffeeScript 1.10.0
(function() {
  var addShop, config, db, getAllShop, getShop, getSomeShop;

  db = require('./../libs/db');

  config = require('./../config/config');

  addShop = function(req, res, next) {
    var body, postData;
    body = req.body;
    postData = {
      shopName: body.shopName != null ? body.shopName : body.shopName = '张师傅的摊点',
      floor: body.floor != null ? body.floor : body.floor = '1',
      type: body.type != null ? body.type : body.type = '0',
      author: req.userInfo != null ? req.userInfo : req.userInfo = {}
    };
    return db.shops.insert(postData, function(err, shop) {
      if (err) {
        return next(err);
      }
      return res.json({
        msg: '添加成功',
        id: shop._id
      });
    });
  };

  getShop = function(req, res, next) {
    var id;
    id = req.params['shopId'];
    return db.shops.findOne({
      _id: id
    }, function(err, shop) {
      if (err) {
        return next(err);
      }
      return res.json(shop);
    });
  };

  getAllShop = function(req, res, next) {
    return db.shops.find({}, function(err, docs) {
      if (err) {
        return next(err);
      }
      return res.json(docs);
    });
  };

  getSomeShop = function(req, res, next) {
    var type;
    type = req.params['type'];
    return db.shops.find({
      type: type
    }, function(err, docs) {
      if (err) {
        return next(err);
      }
      return res.json(docs);
    });
  };

  module.exports = {
    addShop: addShop,
    getShop: getShop,
    getAllShop: getAllShop,
    getSomeShop: getSomeShop
  };

}).call(this);

//# sourceMappingURL=shopBiz.js.map
