// Generated by CoffeeScript 1.10.0
(function() {
  var addShop, commonBiz, config, db, getAllShop, getShop, getSomeShop;

  db = require('./../libs/db');

  config = require('./../config/config');

  commonBiz = require('./commonBiz');

  addShop = function(req, res, next) {
    var body, postData, userInfo;
    body = req.body;
    userInfo = req.userInfo;
    if (!userInfo.is_shopper) {
      return next(commonBiz.customError(400, "您还不是商家,请先申请认证"));
    }
    postData = {
      shopName: body.shopName != null ? body.shopName : body.shopName = '张师傅的摊点',
      floor: body.floor != null ? body.floor : body.floor = '1',
      type: body.type != null ? body.type : body.type = '0',
      shopping_breakfast: body.shopping_breakfast != null ? body.shopping_breakfast : body.shopping_breakfast = false,
      shopping_lunch: body.shopping_lunch != null ? body.shopping_lunch : body.shopping_lunch = false,
      shopping_dinner: body.shopping_dinner != null ? body.shopping_dinner : body.shopping_dinner = false,
      author: {
        _id: userInfo._id,
        name: userInfo.name
      }
    };
    return db.shops.insert(postData, function(err, shop) {
      if (err) {
        return next(err);
      }
      return res.json({
        msg: '添加成功',
        id: shop._id
      });
    });
  };

  getShop = function(req, res, next) {
    var id;
    id = req.params['shopId'];
    return db.shops.findOne({
      _id: id
    }, function(err, shop) {
      if (err) {
        return next(err);
      }
      return res.json(shop);
    });
  };

  getAllShop = function(req, res, next) {
    return db.shops.find({}, function(err, docs) {
      if (err) {
        return next(err);
      }
      return res.json(docs);
    });
  };

  getSomeShop = function(req, res, next) {
    var type;
    type = req.params['type'];
    return db.shops.find({
      type: type
    }, function(err, docs) {
      if (err) {
        return next(err);
      }
      return res.json(docs);
    });
  };

  module.exports = {
    addShop: addShop,
    getShop: getShop,
    getAllShop: getAllShop,
    getSomeShop: getSomeShop
  };

}).call(this);

//# sourceMappingURL=shopBiz.js.map
